chats/models.py
import datetime
from config.db import db

class Chat(db.Model):
    __tablename__ = 'chats_chat'

    id = db.Column(db.BigInteger(), primary_key=True, autoincrement=True)
    name = db.Column(db.String(50), nullable=False)
    description = db.Column(db.String(100), nullable=True)
    pic = db.Column(db.String(50), nullable=True)
    pic1 = db.Column(db.String(50), nullable=True)
    pic2 = db.Column(db.String(50), nullable=True)
    is_bot = db.Column(db.Boolean, default=False)
    is_private = db.Column(db.Boolean, default=False)
    last_content = db.Column(db.String(100), nullable=True)
    unread_messages = db.Column(db.Integer, default=0)
    starter_id = db.Column(db.Integer, db.ForeignKey('User.id'))
    created_at = db.Column(db.DateTime, server_default=db.func.now())
    is_modified = db.Column(db.Boolean, default=False)
    modified_at = db.Column(db.DateTime, onupdate=db.func.now())
    is_deleted = db.Column(db.Boolean, default=False)
    deleted_at = db.Column(db.DateTime, default=datetime.datetime.now())
    restored_at = db.Column(db.DateTime, default=datetime.datetime.now())

    starter = db.relationship('User', backref="chatschatstarter", cascade='all,delete')
    participants = db.relationship('User', backref='chatschatparticipants', secondary='chats_users', viewonly=True, cascade='all,delete')
    messages = db.relationship('Message', backref='chatschatmessages', cascade='all,delete')

    def __init__(self, name, starter_id):
        self.name = name
        self.starter_id = starter_id

    def __repr__(self):
        return 'Chat {}'.format(self.id)


class Message(db.Model):
    __tablename__ = 'chats_message'

    id = db.Column(db.BigInteger(), primary_key=True, autoincrement=True)
    idx = db.Column(db.Text(), nullable=True)
    content = db.Column(db.Text(), nullable=True)
    attachment = db.Column(db.String(50), nullable=True)
    created_at = db.Column(db.DateTime, server_default=db.func.now(), nullable=False)
    is_read = db.Column(db.Boolean, default=False, nullable=False)
    read_at = db.Column(db.DateTime, server_default=db.func.now(), nullable=False)
    is_deleted = db.Column(db.Boolean, default=False, nullable=False)
    deleted_at = db.Column(db.DateTime, server_default=db.func.now(), nullable=False)
    chat_id = db.Column(db.Integer, db.ForeignKey('chats_chat.id'))
    sender_id = db.Column(db.Integer, db.ForeignKey('User.id'))

    chat = db.relationship("Chat", backref="chatsmessagechat", viewonly=True, cascade='all,delete')
    sender = db.relationship('User', backref="chatsmessagesender", cascade='all,delete')

    def __init__(self, content, attachment, chat_id, sender_id):
        self.content = content
        self.attachment = attachment
        self.chat_id = chat_id
        self.sender_id = sender_id

    def __repr__(self):
        return 'Message {}'.format(self.id)

chats/__init__.py
from flask import Blueprint

bp = Blueprint('chats', __name__)

from chats import routes

chats/controllers.py
# """
# API functions
# """
from sqlalchemy import desc, text
from sqlalchemy.dialects.postgresql import insert
from .models import db, Chat, Message
from accounts.models import User, ChatsUsers


class ChatController:
    def __init__():
        pass

    def get_chats(name, last):
        """
        Look up chats generally given a chat name as filter
        Important for joining existing chats
        """
        chats = Chat.query.filter(Chat.name.icontains(
            name)).order_by(desc('modified_at')).limit(last)
        return chats if chats else []

    def get_user_chats(user_id, name, last):
        """
        Look up chats given a user id and chat name.
        This helps users easily search and find chats in their rooms
        """
        chats = Chat.query.filter(Chat.participants.any(
            id=user_id), Chat.name.icontains(name)).order_by(desc('modified_at')).limit(last).all()
        return chats if chats else []

    def get_chat(id):
        """Look up a chat given a chat id."""
        chat = Chat.query.filter_by(id=id).first()
        return chat if chat else []

    def get_user_chat(user_id, chat_name):
        """Look up a chat given user id and chat name."""
        chat = Chat.query.filter(Chat.participants.any(
            id=user_id), Chat.name.icontains(chat_name)).first()
        return chat if chat else []

    def get_chats_names(name):
        """Look up chats given a name."""
        chats = Chat.query.filter(Chat.name.icontains(name))
        return chats if chats else []

    def create_chat(name, starter_id, user_ids, is_private, is_bot):
        """Start a new chat"""
        userids = user_ids.split(',')
        insert_stmt = text(
            "INSERT INTO chats_chat(name,starter_id,is_bot,is_private,is_deleted,unread_messages) values(:name,:starter_id,:is_bot,:is_private,:is_deleted,:unread_messages) returning(chats_chat.id)")
        db.session.execute(
            insert_stmt, {'name':name,'starter_id':starter_id,'is_bot':is_bot,'is_private':is_private,'is_deleted':False,'unread_messages':0})
        select_stmt = text("SELECT * FROM chats_chat WHERE name = :name")
        res = db.session.execute(select_stmt, {'name': name})
        user = User.query.filter_by(id=starter_id).first()
        if res:
            chatid = res.fetchone()[0]
            # if is_bot:
            #     user.hasAssist = True
            entries = []
            entries.append([chatid, starter_id])
            for uid in userids:
                entries.append([chatid, uid])
            db.session.execute(
                ChatsUsers.__table__.insert(),
                [{'chat_id': chatid, 'user_id': uid}
                    for chatid, uid in entries]
            )
            db.session.commit()
            return chatid

    def create_chat_with_usernames(name, starter_id, user_names):
        """Start a new chat with usernames"""
        starter = User.query.filter_by(id=starter_id).first()
        usernames = user_names.split(',')
        users = []
        users.append(starter)
        for username in usernames:
            user = User.query.filter_by(username=username).first()
            users.append(user)
        chat = Chat(name, starter_id)
        db.session.add(chat)
        for user in users:
            chat.participants.append(user)
        db.session.commit()

    def create_chat_private(name, starter_id, user_id):
        """Start a private chat"""
        insert_stmt = text(
            "INSERT INTO chats_chat(name,starter_id) values(:name,:starter_id) returning(chats_chat.id)")
        db.session.execute(
            insert_stmt, {'name': name, 'starter_id': starter_id})
        select_stmt = text("SELECT * FROM chats_chat WHERE name = :name")
        res = db.session.execute(select_stmt, {'name': name})
        if res:
            chatid = res.fetchone()[0]
            # print('new chatid: " ', chatid)
            db.session.execute(
                ChatsUsers.__table__.insert(), [
                    {'chat_id': chatid, 'user_id': starter_id},
                    {'chat_id': chatid, 'user_id': user_id}
                ]
            )
            db.session.commit()

    def update_chat(id, name, description):
        """Change chat name and description"""
        chat = Chat.query.filter_by(id=id).first()
        chat.name = name
        chat.description = description
        db.session.commit()

    def update_chat_pic(user_id, id, pic):
        """Change chat photo"""
        chat = Chat.query.filter_by(id=id).first()
        if chat.is_private == True and user_id == chat.starter_id:
            chat.pic1 = pic
        elif chat.is_private == True and user_id != chat.starter_id:
            chat.pic2 = pic
        elif chat.is_private == False:
            chat.pic = pic
        else:
            chat.pic = pic
        db.session.commit()

    def delete_chat(id, username):
        """Do a soft delete on a chat by starter or admin"""
        chat = Chat.query.filter_by(id=id).first()
        user = User.query.filter_by(username=username).first()
        if chat.starter_id == user.id:
            chat.is_deleted = True
        elif user.is_admin == True:
            chat.is_deleted = True
            db.session.commit()

    def remove_chat(id, username):
        """Delete a chat completely"""
        chat = Chat.query.filter_by(id=id).first()
        user = User.query.filter_by(username=username).first()
        if user.is_admin == True:
            db.session.delete(chat)
            db.session.commit()

    def join_chat(chat_id, user_ids):
        """Join a chat room"""
        chat = Chat.query.filter_by(id=chat_id).first()
        userids = user_ids.split(',')
        if len(chat.participants) + len(userids) > 2:
            chat.is_private = False
        else:
            chat.is_private = True
        entries = []
        for uid in userids:
            entries.append([chat_id, uid])
        db.session.execute(
            ChatsUsers.__table__.insert(),
            [{'chat_id': chat_id, 'user_id': uid} for chat_id, uid in entries]
        )
        db.session.commit()

    def join_chat_with_usernames(chat_id, user_names):
        """Join a chat room with user name"""
        chat = Chat.query.filter_by(id=chat_id).first()
        usernames = user_names.split(',')
        users = []
        for username in usernames:
            user = User.query.filter_by(username=username).first()
            users.append(user)
        for user in users:
            chat.participants.append(user)
        db.session.commit()

    def leave_chat(chat_id, user_id):
        """Leave chat room"""
        delete_stmt = text(
            "DELETE FROM chats_users WHERE chat_id=:chat_id AND user_id=:user_id")
        delete_values = {'chat_id': chat_id, 'user_id': user_id}
        db.session.execute(delete_stmt, delete_values)
        chat = Chat.query.filter_by(id=chat_id).first()
        if len(chat.participants) > 2:
            chat.is_private = False
        else:
            chat.is_private = True
        db.session.commit()
        # print('participants: ',chat.participants)

    def create_message(content, attachment, chat_id, sender_id):
        """Create message"""
        msg = Message(content, attachment, chat_id, sender_id)
        msgs = Message.query.filter_by(chat_id=chat_id, is_read=False).count()
        chat = Chat.query.filter_by(id=chat_id).first()
        chat.last_content = content[0:20]+'...'
        chat.unread_messages = msgs + 1
        chat.modified_at = db.func.now()
        db.session.add(msg)
        db.session.commit()
        return msg.id

    def create_message_upsert(data):
        """Create a new message as push from offline device"""
        stmt = insert(Message).values(data)
        stmt = stmt.on_conflict_do_update(
            index_elements=['id'],
            set_={
                "content": stmt.excluded.content,
            }
        )
        db.session.execute(stmt)
        db.session.commit()

    def get_messages():
        """Get all messages"""
        message = Message.query.all()
        return message if message else []

    def get_chat_messages(chat_id, content, last):
        """Get messages for a selected chat by id """
        msgs = Message.query.filter(Message.chat_id==chat_id, Message.content.icontains(
            content)).order_by(desc('created_at')).limit(last).all()[::-1]
        return msgs if msgs else []

    def get_message(id):
        """Look up a message given a message id."""
        message = Message.query.filter_by(id=id).first()
        return message if message else []

    def count_unread_messages(user_id):
        """Count all unread messages of user """
        count = Message.query.filter_by(sender_id=user_id, is_read=False).count()
        return count if count else []

    def read_message(id):
        """Flag message status as read"""
        message = Message.query.filter_by(id=id).first()
        message.is_read = True
        db.session.commit()

    def read_messages(chat_id):
        """Flag chat messages status as read"""
        chat = Chat.query.filter_by(id=chat_id).first()
        chat.unread_messages = 0
        messages = Message.query.filter_by(chat_id=chat_id, is_read=False)
        for msg in messages:
            msg.is_read = True
        db.session.commit()

    def delete_message(id):
        """Show message status as deleted"""
        message = Message.query.filter_by(id=id).first()
        message.is_deleted = True
        db.session.commit()

chats/routes.py
from flask import request, jsonify, redirect, render_template, url_for, flash, session
from chats import bp
from chats.controllers import ChatController


@bp.route('/chat')
@bp.route('/chat/<chat_id>')
def chat(chat_id=''):
    user_id = session['user_id']
    user_name = session['user_name']
    all_chats = ChatController.get_chats()
    chats = ChatController.get_user_chats(user_id)
    chat = None
    participants = None
    messages = None
    if chat_id != '':
        chat = ChatController.get_chat(chat_id)
        participants = chat.participants
        messages = chat.messages
    return render_template('chat.html', user_id=user_id, user_name=user_name, all_chats=all_chats, chats=chats, chat=chat, participants=participants, messages=messages)


@bp.route('/chat/create', methods=['GET', 'POST'])
def create_chat():
    user_id = session['user_id']
    if request.method == 'POST':
        name = request.form.get('name')
        chat = ChatController.create_chat(name,user_id)
        if chat:
            flash('Chat already exists!', category='error')

            return redirect(url_for('chats.chat'))
    return render_template('create_chat.html')

@bp.route('/chat/join/<chat_id>')
def join_chat(chat_id=''):
    user_id = session['user_id']
    if user_id != '' and chat_id != '':
        chat = ChatController.get_chat(chat_id)
        if chat:
            # ChatController.join_chat(chat_id, user_id)
            return redirect(url_for('chats.chat'))
    return render_template('chat.html')

@bp.route('/chat/leave/<chat_id>')
def leave_chat(chat_id=''):
    user_id = session['user_id']
    if user_id != '' and chat_id != '':
        chat = ChatController.get_chat(chat_id)
        if chat:
            # ChatController.leave_chat(chat_id, user_id)
            return redirect(url_for('chats.chat'))
    return render_template('chat.html')

templates/auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{url_for("static", filename="css/styles.css")}}" rel="stylesheet" />
    <title>OpenChat {% block title %}{% endblock %}</title>

</head>
<body>
    <header>
        <nav>
            <div>OpenChat</div>
            <a href="{{url_for("users.signup")}}">Sign up</a>
            <a href="{{url_for("users.signin")}}">Sign in</a>
        </nav>
    </header>

    <main>
        <div class="main-container">
            <div id="chats-list"></div>
            {% block content %}{% endblock %}
        </div>
    </main>

    <footer>
        @ OpenChat
    </footer>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="{{url_for('static', filename='css/styles.css')}}" rel="stylesheet" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <title>OpenChat {% block title %}{% endblock %}</title>

    {% block head %} {% endblock %}
</head>
<body>
    <header>
        <nav>
            <div>OpenChat {{ user_name }}</div>
            <a href="{{url_for('chats.chat')}}">Chat</a> |
            <a href="{{url_for('chats.create_chat')}}">Create Chat</a> |
            <a href="#" id="modal-open">Join Chat</a> |
            <a href="{{url_for('users.signout')}}">Sign out</a>
        </nav>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        @ OpenChat
    </footer>

</body>
</html>

templates/chat.html
{% extends "base.html" %}

{% block title %}
Chat
{% endblock %}

{% block content %}

<input type="hidden" id="user_id" value="{{ user_id }}" />
<input type="hidden" id="user_name" value="{{ user_name }}" />

<div class="main-container">
    <div id="chats-list">
        <ul id="chats-list">
            {% for chat in chats %}
                <a href="{{ url_for('chats.chat', chat_id=chat.id)}}">
                    <li>{{ chat.name }}</li>
                </a>
            {% endfor %}
        </ul>
    </div>
    <div id="chat-container">
        <div>
            {% if chat %}
            <input type="hidden" id="chat_id" value="{{ chat.id }}" />
            <h1>{{ chat.name }}</h1>
            <a href="{{url_for('chats.leave_chat', chat_id=chat.id)}}" id="leave-chat">Leave Chat</a>
            {% endif %}

            <p>Participants</p>
            {% if participants %}
                {% for participant in participants %}
                    {{ participant.username }}
                {% endfor %}
            {% endif %}
        </div>
        <div id="chat">
            {% if messages %}
                {% for message in messages %}
                    {{ message.content }} <br />
                {% endfor %}
            {% endif %}
        </div>
        <div id="message-form">
            <input type="text" id="message" placeholder="Type here..." />
        </div>
    </div>
</div>

<div id="modal-container" class="modal">

    <div class="modal-content">
      <span class="close">&times;</span>
      <div id="form-container">
        <h1>Join Chat</h1>
        <div>
            <form id="join-form">
                {% for cht in all_chats %}
                    {% if cht %}
                    <p>{{ cht.name }} ID: {{ cht.id }}</p>
                    {% endif %}
                {% endfor %}
                <input type="text" name="join_chat_id" />
                <button>Join</button>
            </form>
        </div>
    </div>
    </div>
  
  </div>

<script src="{{url_for('static', filename='js/chat.js')}}"></script>

{% endblock %}

templates/create_chat.html
{% extends "base.html" %}

{% block title %}
Create Chat
{% endblock %}

{% block content %}

<div id="form-container">
    <h1>Create Chat</h1>
    <form method="POST" id="create-chat-form">
        <div>
            <label>Name</label> <br />
            <input id="name" name="name" type="text" />
        </div>
        <div>
            <label>Description</label><br />
            <input id="description" name="description" type="text" />
        </div>
        <div>
            <button type="submit">Create</button>
        </div>
    </form>
</div>

{% endblock %}

templates/index.html
{% extends "auth.html" %}

{% block title %}
Home
{% endblock %}

{% block content %}

    <h1>Home</h1>

{% endblock %}

templates/signin.html
{% extends "auth.html" %}

{% block title %}
Sign in
{% endblock %}

{% block content %}

<div id="form-container">
    <h1>Sign in</h1>
    <div>
        <form method="POST">
            <div>
                <label>Username</label> <br />
                <input type="text" id="username" name="username" />
            </div>
            <div>
                <label>Password</label> <br />
                <input type="password" id="password" name="password" />
            </div>
            <div>
                <button type="submit">Sign in</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/signup.html
{% extends "auth.html" %}

{% block title %}
Sign up
{% endblock %}

{% block content %}

<div id="form-container">
    <h1>Sign up</h1>
    <div>
        <form method="POST">
            <div>
                <label>Username</label> <br />
                <input type="text" id="username" name="username" />
            </div>
            <div>
                <label>Password</label> <br />
                <input type="password" id="password" name="password" />
            </div>
            <div>
                <button type="submit">Sign up</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}